spring.application.name=primavera
server.port=8081

# Le agregamos el puerto por defecto (3306) y la instrucción para crear la BD si no existe
spring.datasource.url=jdbc:mysql://localhost:3306/otec_primavera?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=${DB_MYSQL_PASSWORD}

# Muestra el SQL en consola (excelente para depurar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Esto le dice a Spring que cree las tablas basadas en los @Entity
spring.jpa.hibernate.ddl-auto=update