spring.application.name=primavera
server.port=8081

# Conexion MySQL y creacion de BD si no existe
spring.datasource.url=jdbc:mysql://localhost:3306/otec_primavera?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=${DB_MYSQL_PASSWORD}

# Mostrar SQL en consola para depuracion
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Crear/actualizar tablas segun entidades
spring.jpa.hibernate.ddl-auto=update